package org.balch.recipes.core.models

import ai.koog.agents.core.tools.annotations.LLMDescription
import android.os.Parcelable
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Serializable
import org.balch.recipes.ui.theme.AccentYellow
import org.balch.recipes.ui.theme.DarkBackground
import org.balch.recipes.ui.theme.DeepBrown
import org.balch.recipes.ui.theme.FreshGreen
import org.balch.recipes.ui.theme.LightBackground
import org.balch.recipes.ui.theme.StrongTeal
import org.balch.recipes.ui.theme.WarmOrange

@LLMDescription("Represents a category or area of Android development topics (Theme, Navigation, Architecture, Testing, Compose)")
@Parcelize
enum class CodeArea : Parcelable {
    Theme,
    Navigation,
    Architecture,
    Testing,
    Compose,

}

/**
 * Returns the theme-aware color for this CodeArea based on the current MaterialTheme.
 * Uses semantically appropriate colors that work well with the warm, food-themed palette
 * and are guaranteed to be defined in both custom and dynamic color schemes.
 */
@Composable
fun CodeArea.color(): Color {
    return when (this) {
        CodeArea.Theme -> WarmOrange
        CodeArea.Navigation -> FreshGreen
        CodeArea.Architecture -> DeepBrown
        CodeArea.Testing -> AccentYellow
        CodeArea.Compose -> StrongTeal
    }
}

@Composable
fun CodeArea.textColor(): Color {
    return when (this) {
        CodeArea.Architecture -> LightBackground
        else -> DarkBackground
    }
}

@LLMDescription("Represents a code recipe or tutorial demonstrating Android development techniques and patterns")
@Parcelize
@Serializable
data class CodeRecipe(
    @property:LLMDescription("Unique index number for the code recipe")
    val index: Int,
    @property:LLMDescription("The development area or category this code recipe belongs to (Theme, Navigation, Architecture, Testing, or Compose)")
    val area: CodeArea,
    @property:LLMDescription("The title of the code recipe")
    val title: String,
    @property:LLMDescription("A description explaining what this code recipe demonstrates")
    val description: String,
    @property:LLMDescription("Optional file name associated with this code recipe")
    val fileName: String? = null,
    @property:LLMDescription("The actual code snippet or example code")
    val codeSnippet: String = "",
    @property:LLMDescription("True if this code recipe was generated by the AI")
    val aiGenerated: Boolean = false,
): UniqueItem, Parcelable {
    @IgnoredOnParcel
    override val id: String by lazy { index.toString() }
}